[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
basket_vault = "5p7G79qSFHWFKiqK2LjeMLFWpPPATNxBroZnv8Do3QZB"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test:ts"

[hooks]
